module.exports = {
  apps: [
    {
      name: "speech",
      script: "app/backend/app.py",
      interpreter: "python3",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 10000,
        RUNNING_IN_PRODUCTION: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/pm2-speech-error.log",
      out_file: "./logs/pm2-speech-out.log",
      log_file: "./logs/pm2-speech-combined.log",
      time: true,
      env_production: {
        NODE_ENV: "production",
        RUNNING_IN_PRODUCTION: "true",
        PORT: 10000,
      },
    },
    {
      name: "speech-api",
      script: "app/backend/app.py",
      interpreter: "python3",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 10001,
        RUNNING_IN_PRODUCTION: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/pm2-speech-api-error.log",
      out_file: "./logs/pm2-speech-api-out.log",
      log_file: "./logs/pm2-speech-api-combined.log",
      time: true,
      env_production: {
        NODE_ENV: "production",
        RUNNING_IN_PRODUCTION: "true",
        PORT: 10001,
      },
    },
    {
      name: "converse",
      script: "app/backend/app.py",
      interpreter: "python3",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 10002,
        RUNNING_IN_PRODUCTION: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/pm2-converse-error.log",
      out_file: "./logs/pm2-converse-out.log",
      log_file: "./logs/pm2-converse-combined.log",
      time: true,
      env_production: {
        NODE_ENV: "production",
        RUNNING_IN_PRODUCTION: "true",
        PORT: 10002,
      },
    },
    {
      name: "converse-api",
      script: "app/backend/app.py",
      interpreter: "python3",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 10003,
        RUNNING_IN_PRODUCTION: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/pm2-converse-api-error.log",
      out_file: "./logs/pm2-converse-api-out.log",
      log_file: "./logs/pm2-converse-api-combined.log",
      time: true,
      env_production: {
        NODE_ENV: "production",
        RUNNING_IN_PRODUCTION: "true",
        PORT: 10003,
      },
    },
  ],
};
