module.exports = {
  apps: [
    {
      name: "aisearch-backend",
      script: "app/backend/app.py",
      interpreter: ".venv/bin/python",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 20000,
        RUNNING_IN_PRODUCTION: "true",
        CORS_ORIGINS:
          "https://converse.destinpq.com,https://converse-api.destinpq.com,https://converse-monitor.destinpq.com",
        API_BASE_URL: "https://converse-api.destinpq.com",
        FRONTEND_URL: "https://converse.destinpq.com",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/backend-error.log",
      out_file: "./logs/backend-out.log",
      log_file: "./logs/backend-combined.log",
      time: true,
    },
    {
      name: "aisearch-health",
      script: "app/backend/app.py",
      interpreter: ".venv/bin/python",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 20001,
        RUNNING_IN_PRODUCTION: "true",
        HEALTH_CHECK_MODE: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      error_file: "./logs/health-error.log",
      out_file: "./logs/health-out.log",
      log_file: "./logs/health-combined.log",
      time: true,
    },
    {
      name: "aisearch-frontend",
      script: "app/backend/app.py",
      interpreter: ".venv/bin/python",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 20002,
        RUNNING_IN_PRODUCTION: "true",
        FRONTEND_MODE: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "1G",
      error_file: "./logs/frontend-error.log",
      out_file: "./logs/frontend-out.log",
      log_file: "./logs/frontend-combined.log",
      time: true,
    },
    {
      name: "aisearch-monitor",
      script: "app/backend/app.py",
      interpreter: ".venv/bin/python",
      cwd: "/home/azureuser/aisearch-openai-rag-audio",
      env: {
        PYTHONPATH: "/home/azureuser/aisearch-openai-rag-audio",
        PORT: 20003,
        RUNNING_IN_PRODUCTION: "true",
        MONITORING_MODE: "true",
      },
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: "512M",
      error_file: "./logs/monitor-error.log",
      out_file: "./logs/monitor-out.log",
      log_file: "./logs/monitor-combined.log",
      time: true,
    },
  ],
};
